# Generated by Django 4.0 on 2021-12-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalDescription', models.CharField(max_length=255)),
                ('animalColour', models.CharField(max_length=255)),
                ('animalAge', models.IntegerField()),
                ('animalGender', models.CharField(max_length=128)),
                ('animalLocation', models.CharField(max_length=255)),
                ('animalWeight', models.IntegerField()),
                ('animalHeight', models.DecimalField(decimal_places=2, max_digits=2)),
                ('animalPicture', models.CharField(max_length=600)),
                ('animalNasal', models.CharField(max_length=128)),
            ],
        ),
    ]
